apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $data := "" }}
  {{- if eq .Values.microservice "frontend" }}
  {{- $data = .Files.Get "cfg/frontendconfig.yml" }}
  {{- end }}
  {{- if eq .Values.microservice "backend" }}
  {{- $data = .Files.Get "cfg/backendconfig.yml" }}
  DB_HOST: postgres-service
  {{- end }}
  {{- $cfg := fromYaml $data }}
  {{- range $k, $v := $cfg.config }}
  {{ $k }}: {{ $v }}
  {{- end }}
  