apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.port.containerPort }}
        resources:
          requests:
            cpu: "50m"
            memory: "115Mi"
          limits:
            cpu: "110m"
            memory: "128Mi"
        envFrom:
          - configMapRef:
             name: {{ .Release.Name }}-configmap
          {{- if or (eq .Values.microservice "backend") (eq .Values.microservice "database") }}   
          - secretRef:
             name: {{ .Release.Name }}-secret  
          {{- end }}
        imagePullPolicy: Always