{{- if eq .Values.microservice "database" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
    {{- $data := "" }}
    {{- if or (eq .Values.microservice "backend") (eq .Values.microservice "database") }}
    {{- $data = .Files.Get "cfg/databasesecret.yml" }}
    {{- end }}
    {{- $cfg := fromYaml $data }}   
    {{- range $k, $v := $cfg.secret }}
    {{ $k }}: {{ $v }}
    {{- end }}
{{- end }}