apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-pod
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    {{- if eq .Values.microservice "backend" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}